# Generated by Django 4.2.7 on 2023-11-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0002_rename_event_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('eventStartDate', models.DateTimeField()),
                ('venue_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
