# Generated by Django 4.2.7 on 2023-11-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0003_event_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventStartDate',
        ),
    ]
