# Generated by Django 4.2.7 on 2023-11-30 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0004_remove_event_eventstartdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventStartDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
