# Generated by Django 4.2.7 on 2023-12-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0005_event_eventstartdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='FavoriteEvent',
        ),
    ]
