# Generated by Django 4.2.7 on 2023-12-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0006_rename_event_favoriteevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteevent',
            name='eventStartDate',
        ),
    ]
