# Generated by Django 4.2.7 on 2023-12-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0007_remove_favoriteevent_eventstartdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteevent',
            name='venue_name',
        ),
        migrations.AddField(
            model_name='favoriteevent',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoriteevent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
